version: '3'
services:
  app:
    container_name: bandrek-app
    restart: on-failure
    depends_on:
      - mariadb
    links:
      - mariadb
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - bandrek
  mariadb:
    image: mariadb
    container_name: bandrek-mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: bandrek
    volumes:
      - /data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bandrek

networks:
  bandrek:
    driver: bridge