x-common-general: &common-general
  restart: unless-stopped
  deploy:
    resources:
      limits:
        memory: 512M

services:
  app:
    <<: *common-general
    image: ghcr.io/stegripe/bandrek:latest-dev
    container_name: bandrek-app
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - bandrek

  mariadb:
    image: mariadb
    container_name: bandrek-mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: bandrek
    volumes:
      - /data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bandrek

networks:
  bandrek:
    driver: bridge
